[project]
name = "tcwpy"
version = "0.1.0"
authors = [{name = "Tom Stephen", email = "tom@outerloop.io"}]
description = "Read a TransCAD fixed-format binary table to a pandas DataFrame."
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.13"
dependencies = [
    "pandas",
    "numpy",
]

[dependency-groups]
dev = [
    "pytest"
]
