name: Tests on all platforms

on: [push]

jobs:
  testing:
    needs: linting
    runs-on: ${{ matrix.os}}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
        os: [windows-latest, ubuntu-latest, macos-latest]

      max-parallel: 20
    steps:
    - uses: actions/checkout@v4
    - name: Set Python environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        python -m uv pip install -e .[dev]
    
    - name: Run tests on all versions and operating systems
      run: python -m pytest tests/tests.py --durations=50 --verbose